### ISSUE TITLE
Block an app that show the dot

### ISSUE THREAD

**Issue by zeuss574** [gilbsgilbs/LocationIndicatorWhitelist#14]
Hello, can you make a feature that blacklist the app that I want to block the dot? Because your app now just support whitelist. Thank you!

**Comment by gilbsgilbs** [comment]
I don't understand your feature request. This app allows other apps to access the location without triggering the notification dot. Isn't this exactly what you're suggesting?

**Comment by zeuss574** [comment]
Sorry for make you confused. My suggestion is create a feature same as this app now but in reverse. It means that we will select app to hide the notification dot of the app. Thank you!

**Comment by gilbsgilbs** [comment]
You mean hide the notification dot for *all* apps, and just pick apps that can show the dot? I'm not sure I see the use-case.

**Comment by zeuss574** [comment]
No, I mean show the notification for all apps and pick apps to hide the dot.

**Comment by gilbsgilbs** [comment]
This is already what this app does 😄.

**Comment by gilbsgilbs** [comment]
TBF the app name was poorly chosen by me, for multiple reasons. Would probably need a rename, but I don't think I care enough.
